language: ruby
rvm:
- 2.4.0
install: gem install jekyll jekyll-paginate jekyll-seo-tag html-proofer
script: jekyll build

# 分支白名单
branches:
  only:
  - gh-pages     # 测试 gh-pages 分支
  - /pages-(.*)/ # 测试以 "pages-" 开头的所有分支

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # 为 html-proofer 的安装加速
